### ISSUE TITLE
[ Feature ] - Propagate credential change

### ISSUE THREAD

**Issue by FranckSallet** [wallix/terraform-provider-wallix-bastion#18]
**Is your feature request related to a problem? Please describe.**
I use a global account to manage password of active directory accounts.
The problem appears when I create a "wallix-bastion_domain_account_credential resource", I cannot propagate the password to the Active Directory account like I could do on the GUI. We therefore need manual action on the bastion for the account to be fully functional.

**Describe the solution you'd like**
add a boolean parameter like "propagate_credential_change" in the "wallix-bastion_domain_account_credential" resource

Regards

**Comment by bsimonWallix** [comment]
After study, the endpoint exist on the API but not yet implemented on the Terraform provider.

![image](https://github.com/wallix/terraform-provider-wallix-bastion/assets/130672981/d21eef3c-a739-453b-95d7-aeeda4a8799b)

I am going to see with the team how we can add it for the next release.

**Comment by FranckSallet** [comment]
thank you for the reply
in this case, you must repair the destruction of the resource when changing the password. cf issue 17

**Comment by bsimonWallix** [comment]
It is tracked for fix and improvment for next release.

**Comment by moulip** [comment]
Hi @FranckSallet,

I'm currently looking into your enhancement request. I need some details about your usecase.
Let me expand on what I have understood and correct me if I'm mistaken.

You have an already existing account in your AD.
You want to create it in your Bastion with TF, creaate a new password for that account, and propagate it to the AD.
Is that right ?

**Comment by FranckSallet** [comment]
Hi @moulip 

yes, that's exactly it.
We need to manage AD account passwords through the password manager with TF.
The password must also be able to be changed through the interface or via the password policy.

regards

**Comment by moulip** [comment]
> Hi @moulip
> 
> yes, that's exactly it. We need to manage AD account passwords through the password manager with TF. The password must also be able to be changed through the interface or via the password policy.
> 
> regards

I completely get your use-case. I just want to make sure that we agree on the fact that the account already exists in the AD with a password already set and as soon as you create it for the first time in the Bastion, you will create it with another password which will replace the previously set password in AD upon creation.

**Comment by FranckSallet** [comment]
Hi @moulip

We are completely agree about my use case.
We have a already Active Directory account with a password.
After that we want to manage the password with the "Password Manager" and the "Password Policy".

Regards

**Comment by moulip** [comment]
All right will dig into it now ;-)

**Comment by moulip** [comment]
Hi @FranckSallet !

Long time no talk sorry for that. I have done the task and the provider is now able to propagate the credential change BUT, this has led to find a bug in the Bastion which prevents me from relaasing a new version.
We are on the path of fixing this bug and as from there I'll be able to commit.
Just to keep you updated.

**Comment by FranckSallet** [comment]
Hi @moulip 

great to hear that
This next release of the provider will work with the bastion version 12 ?

**Comment by moulip** [comment]
Will try to do so !

**Comment by FranckSallet** [comment]
Hi @moulip 

Any news or release date ?

Regards

**Comment by bsimonWallix** [comment]
We are just pushing the v0.14.0 - The fix of this is issue wasn't merged as it does need more testing. 

We target a v0.14.1 next week for it.

**Comment by bsimonWallix** [comment]
Hello we just pushed the change from @moulip for this request. 
We are still waiting on the fix on the bastion API. As for now the uuid of the password is lost on change and terraform have issue to keep the state.

**Comment by FranckSallet** [comment]
Bonjour Simon
Merci du retour
ce n'est toujours pas fixé dans la version 12.0.5 du bastion ?
Merci, Franck

**Comment by FranckSallet** [comment]
je ne vois pas l'option "Propagate credential change" dans la documentation de la version 14, c'est normal ?
Merci, Franck

**Comment by bsimonWallix** [comment]
C'est sur la branche develop pour le moment. 
On devrait sortir une nouvelle release sous peu

**Comment by bsimonWallix** [comment]
![image](https://github.com/user-attachments/assets/2a8dac98-99ca-4e40-bdcd-e4612c26cb2f)

It is now published. 
![image](https://github.com/user-attachments/assets/ce9bbf59-4356-4ae8-99ef-a768b17a2f84)

Warning: currently secret associated to this is not tracked. So you will need to add a ignore_changes flag in the code so the secret is not changed each time
