### ISSUE TITLE
[ Feature ] - Accounts

### ISSUE THREAD

**Issue by FranckSallet** [wallix/terraform-provider-wallix-bastion#43]
Bonjour,

Serait-il possible de prévoir d'ajouter à la futur version la ressource "accounts" relative au endpoint "/api/accounts" ?
L'idée est de pouvoir gérer les comptes locaux du bastion. Si je ne me trompte, ce n'est pas possible aujourd'hui.

Merci, Franck

**Comment by moulip** [comment]
Bonjour,

Pourriez-vous préciser le cas d'usage s'il vous plaît ? La route « /api/accounts/ » ne permet de faire que des GET et des DELETE.

**Comment by FranckSallet** [comment]
ah oui j'avais pas vu.
Est ce qu'il y a une ressource terraform pour creer des comptes locaux au wallix ?
je ne parle pas de comptes cible mais de compte de connexion au wallix.
ceux que je peux creer via le menu : Users > Accounts
Merci, Franck

**Comment by moulip** [comment]
Oui il y a la possibilité de les créer avec « wallix-bastion_user ».

**Comment by bilel-mrad** [comment]
Hey all,

Can you please add a terraform resources that handle Targets => Accounts => Global accounts. As of now it is not possible to do so either via the REST API as no POST method has been developed nor terrafrom resources .

Please correct me if I'm wrong .

Thanks

**Comment by bsimonWallix** [comment]
Hello, are you referring to the following api endpoint ? **/api/accounts/**

If it's the case, this is intended, it is used as a search endpoint to list and filter "accounts", there is a delete option there also but the creation modification etc. are handled by sub-resources: 

- device accounts,
- domain accoutns,
- applications accounts

Those resources have also link with other sub-resources linked to credentials ( password, sshkey, etc.)

- device accounts credentials
- domain accoutns credentials
- applications accounts credentials
 
So this is both supported with the API or by the terraform provider. It's just not so much clear in api doc and we plan to add a little text about it in future release of said api doc.

**Comment by bilel-mrad** [comment]
Hey @bsimonWallix thanks for your update, I'm really lost and need help my aim is to automate the creation of Global accounts and then add a password to it see the bellow screenshot . 

I'm struggling to find a related terraform resources or API endpoint that fit my need . Can you please help me if it does exist ? either via terraform or REST API . 


Thanks .

![image](https://github.com/user-attachments/assets/170ca627-a838-48c5-8b63-e8bd3021da2a)

**Comment by bsimonWallix** [comment]
@bilel-mrad  : https://github.com/wallix/Automation_Showroom/blob/main/Terraform/Provisionning/01-Basic/base/target_n_targetgrp.tf

**Comment by bilel-mrad** [comment]
Thanks for sharing @bsimonWallix , it really helps me , I've starting automating stuff related to target group .

**Comment by bsimonWallix** [comment]
I am closing this issue. 

We arranged bastion API documentation for future bastion release to help on the comprehension for the /accounts endpoint.

![image](https://github.com/user-attachments/assets/bc2eff32-c51a-4c74-b452-04722eb8f984)
